import{i as l,S as c}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function u(s){const r="https://pixabay.com/api/",n=`?key=43757343-ba5778b701f459784bea5ede7&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(`${r}${n}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function p(s,r){const o=s.reduce((n,e)=>n+=`<div class="gallery-item">
          <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"  width="360"/></a>
          <div class="info">
              <p>Likes <span></span>${e.likes}</span></p>
              <p>Views <span></span>${e.views}</span></p>
              <p>Comments <span></span>${e.comments}</span></p>
              <p>Downloads <span></span>${e.downloads}</span></p>
          </div>
              </div>`,"");r.insertAdjacentHTML("beforeend",o)}const a={formEL:document.querySelector("#form"),inputEL:document.querySelector("#image-input"),galleryEL:document.querySelector("#gallery"),gallery:document.querySelector(".gallery")};function f(s){s.preventDefault(),a.galleryEL.innerHTML='<span class="loader"></span>';const r=a.inputEL.value.trim();if(r==="")return l.show({title:"⨻",titleSize:"20px",message:"Introduction field please enter the value to search",color:"white",backgroundColor:"red",position:"topRight"});u(r).then(o=>{if(o.totalHits===0)return l.show({title:"⨻",titleSize:"20px",message:'"Sorry, there are no images matching your search query. Please try again!"',color:"white",backgroundColor:"red",position:"topRight"});a.galleryEL.innerHTML="",p(o.hits,a.galleryEL),new c("#gallery a",{captionsData:"alt",captionDelay:250}).refresh()}),a.formEL.reset()}a.formEL.addEventListener("submit",f);
//# sourceMappingURL=commonHelpers.js.map
